version: "3"
services:
  proxy:
    image: zterry95/shadowsocker-client-go
    volumes:
      - ./shadowsocks.json:/etc/shadowsocks/config.json
    ports:
      - "${SS_LOCAL_PORT}:1080"
      - "8123:8123"
    restart: "always" 
