version: "3"
services:
  proxy:
    image: zterry95/shadowsocks-client-go
    volumes:
        #- ./shadowsocks.json:/etc/shadowsocks/config.json
      - ./supervisord.conf:/etc/supervisord.conf
      - ./pgfast:/go/pgfast
      - ./pgfast/pgconfig.toml:/etc/pgconfig.toml
      - ./confd:/etc/confd
    ports:
      - "${SS_LOCAL_PORT}:1080"
      - "8123:8123"
    restart: "always" 
